spring:
  application:
    name: wangzhan
  datasource:
    url: jdbc:sqlite:K:\wz\src\main\resources\bilibili.db
    driver-class-name: org.sqlite.JDBC
    # SQLite 不需要用户名和密码
    username:
    password:
  sql:
    init:
      mode: always
  mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.example.demo.entity
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 可选，用于打印SQL日志
    global-config:
      db-config:
        id-type: auto
        logic-delete-value: 1
        logic-not-delete-value: 0
server:
  port: 8090

cookie: >
  cookie=SESSDATA=54107de1%2C1746361438%2C6ac51%2Ab2CjC3HIdqj_UlsQsSQtgoJyCXUfjMYdvIcRgpAYjVMtwMtMOehkmAc3PSlyWJG-ooqe8SVkg1TGF3SDJ3NlhzNTM5dllIb00tcEg3ZGR6NUFKTzNQeWxzcmZ0bVA3a2NaejBObDh0Y1VWbGg1a21sdTlrMGI1U2FZYkFTcVlBbjc0c2owdDFRODFRIIEC

savePath: D://BiliBili//
outPath: D://BiliBiliOutput//

quark:
  cookies: _UP_A4A_11_=wb9621e3efed45568b3a9bcef63393f5; _UP_30C_6A_=st96b620194ts2dax7sq0ef388yt0eax; _UP_TS_=sg15b5851f62ef76cebf1f3be4284108d17; _UP_E37_B7_=sg15b5851f62ef76cebf1f3be4284108d17; _UP_TG_=st96b620194ts2dax7sq0ef388yt0eax; _UP_335_2B_=1; __pus=7e9d1382aa2727f2a0c79636053f926eAAQtQi7HKWYTbrg09XcFJVAaRvBRehg4iaqkaxLMGxgl2FG31IniTI7HEcvpJiDMiY0SN1nMGVokuaQ43uqI3IhU; __kp=3cd4a5d0-9a8d-11ef-966a-493130579d02; __kps=AARO/QNtfhmN2+I0y1DdF/zt; __ktd=fqxRgQICvdg0nF+M8C+kIQ==; __uid=AARO/QNtfhmN2+I0y1DdF/zt; tfstk=fz1ZCP4g-5FaFVPjGFR2zYtbjHR9gCq5IstXoZbD5hxM5C_cLZ_zWEs1onW2xiUt1CqtinbRvdtGcCi4gMRMHOtXfnRVkgzQV7N5WNdvtuZ7NVFntNASiVmXnBbh31YiW7N5WNXnjI84N1gFl7xymIvMnXAHvFAmsIjDxpYkPcAcmI4eKUTijmcDmDAHrHxDiIjc-bzRoNlePd47OOPYmkqDI3bMjZ_Fty9iBw-EijfFQd-u0Hlmi68NRBmGdbyXqTK6F3I3OfRV-ESeFOrr_i7cytvFgc41qZjOTCdzhPpPK96WQ9rigH16uLADLqcc8B-d4sAuZD8dKN6c6GuqiFC1NK-JLrcvhBfWETjZkzQHsEjvesZ-6hbcy_BWa5oJ79byTgJIDej0ysBZmxvMJe-78yz1EAMhFlBqcxHvKWLeVPTsHxpMJe-78ykxHp4J83a65; __puus=7dc1c66d73ad4f1f33363385338a4224AASzxkJNNvVTMiMJO79eUnzfas33a5cOJb1Lt9iVoBVjjO3k3T+fA7zZhYnWetQZYNRHuEeVZ5rEVtg161EWBX41ShivXqHyhoKNy21Y2C+b5h/gVw74dzMGPpemLvMIh1zLx3XVnIpxjsySA9iY1vt6hG5NVm4RbMJDuWm7x378qpJwD/7Chxw1/NcazL3pRqLx4h6zW4JlSnpmhx3LpN84

wordpress:
  username: ttfire
  password: LsMk 2W5y 3bZq Zcyz b6Jp 6cvo
  url: https://bili-fun.com/